name       : mate-notification-daemon
version    : 1.22.0
release    : 10
source     :
    - https://github.com/mate-desktop/mate-notification-daemon/archive/v1.22.0.tar.gz : 59ffdf214b950fc1b19b3be0a0031576ece8078b0a2e1d565cdfcd033ba0b82b
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Notification Daemon for MATE Desktop
description: |
    XDG Notification Daemon for MATE Desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
    - mate-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
