name       : mate-notification-daemon
version    : 1.20.1
release    : 7
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-notification-daemon-1.20.1.tar.xz : e85cd01f40d238c57b3da30537fbd561102e652f492b20ebfea79938d8e39a43
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : XDG Notifications Daemon for MATE Desktop
description: |
    XDG Notifications Daemon for MATE Desktop
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
