name       : mate-notification-daemon
version    : 1.24.1
release    : 13
source     :
    - https://github.com/mate-desktop/mate-notification-daemon/releases/download/v1.24.1/mate-notification-daemon-1.24.1.tar.xz : 4bf0bbe39b4bc77ea0feb5d8331f6d1c820c9a8e1643e4aeceef96682bca7ff9
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Notification Daemon for MATE Desktop
description: |
    XDG Notification Daemon for MATE Desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
