name       : mate-notification-daemon
version    : 1.16.0
release    : 3
source     :
    - http://pub.mate-desktop.org/releases/1.16/mate-notification-daemon-1.16.0.tar.xz : 8555bc619ec11b44b092a57b47b87efa53cac1cc0173c132eedcc11c68ccdc49
license    : GPL-2.0
component  : desktop.mate
summary    : XDG Notifications Daemon for MATE Desktop
description: |
    XDG Notifications Daemon for MATE Desktop
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
setup      : |
    %apply_patches
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
