name       : mate-notification-daemon
version    : 1.24.2
release    : 14
source     :
    - https://github.com/mate-desktop/mate-notification-daemon/releases/download/v1.24.2/mate-notification-daemon-1.24.2.tar.xz : 58a4193ef8b36024ec0035c3e48e2a08d87c569260317ffef6f12f665048ae0a
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Notification Daemon for MATE Desktop
description: |
    XDG Notification Daemon for MATE Desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
