name       : mate-notification-daemon
version    : 1.27.0
release    : 16
source     :
    - https://github.com/mate-desktop/mate-notification-daemon/releases/download/v1.27.0/mate-notification-daemon-1.27.0.tar.xz : 318229c407ef1106e34b70889b38813b94c4c0f33fa080d223db43205ccdfd52
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Notification Daemon for MATE Desktop
description: |
    XDG Notification Daemon for MATE Desktop
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(mate-desktop-2.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
