name       : mate-notification-daemon
version    : 1.24.0
release    : 12
source     :
    - https://github.com/mate-desktop/mate-notification-daemon/archive/v1.24.0.tar.gz : 5175c5cc65e532c37ea7a73ecd65dfe25705cc4d7cddb25144006f9841ac79ab
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Notification Daemon for MATE Desktop
description: |
    XDG Notification Daemon for MATE Desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
    - mate-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
