name       : mate-notification-daemon
version    : 1.18.0
release    : 4
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-notification-daemon-1.18.0.tar.xz : 4c1f08fa348cdba0b7786a4207b0b4a40d06deb878f3d71ca1c7f71b53da1066
license    : GPL-2.0
component  : desktop.mate
summary    : XDG Notifications Daemon for MATE Desktop
description: |
    XDG Notifications Daemon for MATE Desktop
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
