name       : mate-notification-daemon
version    : 1.20.2
release    : 9
source     :
    - https://github.com/mate-desktop/mate-notification-daemon/archive/v1.20.2.tar.gz : e3307a14ee79ecd149f307218fc5dbd16fc3164db2be35bc45352b82f6774d15
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : XDG Notifications Daemon for MATE Desktop
description: |
    XDG Notifications Daemon for MATE Desktop
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
    - mate-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
