name       : mate-notification-daemon
version    : 1.22.1
release    : 11
source     :
    - https://github.com/mate-desktop/mate-notification-daemon/archive/v1.22.1.tar.gz : e49c00cea13d1f3d71fb250337f4613b62a6d17c540dc1e699508c7f0336f19d
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Notification Daemon for MATE Desktop
description: |
    XDG Notification Daemon for MATE Desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
    - mate-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
